name: test
on:
  push:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - swift:5.5-focal
#          - swiftlang/swift:nightly-main-focal
    container: ${{ matrix.runner }}
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: apt-get -q update && apt-get -q install -y libsqlite3-dev
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run linux tests
        run: swift test
  macOS:
    strategy:
      fail-fast: false
      matrix:
        version:
          - latest
          - latest-stable
    runs-on: macos-11
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.version }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run macOS tests with Thread Sanitizer
        run: swift test --sanitize=thread
